@extends('layout')
@section('body_id','posts-index')
@section("content")
      <div class="article">
      	<article class="post-excerpt">
      		<h2  class="title">
      			<a href="">Laravel XCSRF Token</a>
      		</h2>
      		<div class="excerpt">
      			Laravel stores the current CSRF token in a XSRF-TOKEN cookie that is included with each response generated by the framework. You can use the cookie value to set the X-XSRF-TOKEN request header. This cookie is primarily sent as a convenience since some JavaScript frameworks and libraries, like Angular and Axios, automatically place its value in the X-XSRF-TOKEN header.
      		</div>
      		<a href="" class="read-more">ReadMore</a>
      	</article>

      	<article class="post-excerpt">
      		<h2  class="title">
      			<a href="">Laravel XCSRF Token</a>
      		</h2>
      		<div class="excerpt">
      			Laravel stores the current CSRF token in a XSRF-TOKEN cookie that is included with each response generated by the framework. You can use the cookie value to set the X-XSRF-TOKEN request header. This cookie is primarily sent as a convenience since some JavaScript frameworks and libraries, like Angular and Axios, automatically place its value in the X-XSRF-TOKEN header.
      		</div>
      		<a href="" class="read-more">ReadMore</a>
      	</article>
      	<article class="post-excerpt">
      		<h2  class="title">
      			<a href="">Laravel XCSRF Token</a>
      		</h2>
      		<div class="excerpt">
      			Laravel stores the current CSRF token in a XSRF-TOKEN cookie that is included with each response generated by the framework. You can use the cookie value to set the X-XSRF-TOKEN request header. This cookie is primarily sent as a convenience since some JavaScript frameworks and libraries, like Angular and Axios, automatically place its value in the X-XSRF-TOKEN header.
      		</div>
      		<a href="" class="read-more">ReadMore</a>
      	</article>
      	<article class="post-excerpt">
      		<h2  class="title">
      			<a href="">Laravel XCSRF Token</a>
      		</h2>
      		<div class="excerpt">
      			Laravel stores the current CSRF token in a XSRF-TOKEN cookie that is included with each response generated by the framework. You can use the cookie value to set the X-XSRF-TOKEN request header. This cookie is primarily sent as a convenience since some JavaScript frameworks and libraries, like Angular and Axios, automatically place its value in the X-XSRF-TOKEN header.
      		</div>
      		<a href="" class="read-more">ReadMore</a>
      	</article>
      </div>
@stop